{
    __schema {
        queryType {
            name
        }
        mutationType {
            name
        }
        subscriptionType {
            name
        }
        directives {
            name
            description
            locations
            args {
                name
                type {
                    name
                }
                defaultValue
            }
        }
        types {
            name
            kind
            description
            fields(includeDeprecated: true) {
                name
                description
                args {
                    name
                    type {
                        name
                        kind
                    }
                }
                type {
                    name
                    kind
                }
                isDeprecated
                deprecationReason
            }
            interfaces {
                name
            }
            possibleTypes {
                name
            }
            enumValues(includeDeprecated: true) {
                name
                description
                isDeprecated
                deprecationReason
            }
            inputFields {
                name
                type {
                    name
                    kind
                }
                defaultValue
            }
        }
    }
}